eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流 (向自己注册)
    service-url:
      defaultZone: http://euk3.com:7003/eureka/
    #实例名称
  instance:
    hostname: euk3.com
server:
  port: 7003